import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--epoch', type=int, default=100, help='epoch number')
parser.add_argument('--lr', type=float, default=5e-5, help='learning rate')
parser.add_argument('--batchsize', type=int, default=4, help='training batch size')
parser.add_argument('--trainsize', type=int, default=384, help='training dataset size')
parser.add_argument('--clip', type=float, default=1.0, help='gradient clipping margin')
parser.add_argument('--lr_sched', type=str, default='cosine', choices=['cosine', 'step'], help='learning rate schedule')
parser.add_argument('--min_lr', type=float, default=1e-6, help='minimum learning rate for cosine schedule')
parser.add_argument('--warmup_lr', type=float, default=1e-6, help='warmup start learning rate')
parser.add_argument('--warmup_epochs', type=int, default=5, help='number of warmup epochs')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=100, help='every n epochs decay learning rate')
parser.add_argument('--load_pre', type=str, default='', help='pretrained checkpoint path')
parser.add_argument('--gpu_id', type=str, default='0', help='train use gpu')
parser.add_argument('--image_root', type=str, default='all', help='training dataset mode: all / RGBT / LightField, or a custom RGB root path')
parser.add_argument('--rgb_root', type=str, default='', help='training rgb image root')
parser.add_argument('--depth_root', type=str, default='', help='training thermal image root')
parser.add_argument('--gt_root', type=str, default='', help='training gt image root')
parser.add_argument('--test_rgb_root', type=str, default='', help='test rgb image root')
parser.add_argument('--test_depth_root', type=str, default='', help='test thermal image root')
parser.add_argument('--test_gt_root', type=str, default='', help='test gt image root')
parser.add_argument('--save_path', type=str, default='./Results/Result_UMFNet/', help='path to save models and logs')
parser.add_argument('--test_start_epoch', type=int, default=1, help='start evaluation from this epoch')
parser.add_argument('--resume', type=str, default='', help='resume training from checkpoint path')
parser.add_argument('--resume_mode', type=str, default='none', choices=['none', 'resume', 'finetune'], help='resume: restore model and optimizer state; finetune: load model only')
opt = parser.parse_args()
